apiVersion: rhtas.redhat.com/v1alpha1
kind: ModelValidation
metadata:
  labels:
    app.kubernetes.io/name: rhtas-operator
    app.kubernetes.io/managed-by: kustomize
  name: modelvalidation-sample
spec:
  # TODO(user): Add fields here
