apiVersion: rhtas.redhat.com/v1alpha1
kind: ModelValidation
metadata:
  labels:
    app.kubernetes.io/name: rhtas-operator
    app.kubernetes.io/managed-by: kustomize
  name: modelvalidation-sample
spec:
  model:
    path: "/models/example-model"
    signaturePath: "/models/example-model/signature.sig"
  config:
    sigstore:
      certificateIdentity: "name@example.com"
      certificateOidcIssuer: "https://accounts.example.com"
